[package]
name = "glob-tree"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.3", features = ["async_tokio"] }
regex = "1.11.1"

[[bench]]
name = "main"
harness = false
